In [1]:
import pandas as pd
import sys
import os

sys.path.append(os.path.join(os.getcwd(), '..', 'script'))

from feature_engineering import feature_engineering, save_featured_data

df_cleaned = pd.read_csv('../output/1.data_cleaning/valid_filtered_covid19_data.csv')
df_featured = feature_engineering(df_cleaned)

output_dir = os.path.join(os.getcwd(), '..', 'output', '3.feature_engineering')
save_featured_data(df_featured, output_dir)

df_featured.head()

,country,date,confirmed_cases,deaths,recoveries,total_confirmed,total_deaths,total_recoveries,case_fatality_rate,recovery_rate
0,Indonesia,2022-09-20,901,491,220,3284,1336,3461,0.544950,0.244173
1,Italy,2020-06-21,689,509,216,2758,2009,299,0.738752,0.313498
2,Norway,2020-02-08,55,45,5,1218,248,2347,0.818182,0.090909
3,Spain,2021-03-03,766,714,749,6973,3943,1697,0.932115,0.977807
4,Malaysia,2021-01-15,119,110,4,5469,3629,1590,0.924370,0.033613